export const listamonedas=[
  {
    "moneda_clave": "MXN",
    "moneda_nombre": "Peso Mexicano",
    "moneda_nombre_singular": "peso",
    "moneda_nombre_plural": "pesos",
    "moneda_denominacion": "M.N.",
    "moneda_simbolo": "$",
    "moneda_decimales": "2",
    "moneda_porcentaje_variacion": "5",
  },
  {
    "moneda_clave": "USD",
    "moneda_nombre": "Dolar americano",
    "moneda_nombre_singular": "dolar de los E.U.A.",
    "moneda_nombre_plural": "dólares de los E.U.A.",
    "moneda_denominacion": "M.E.",
    "moneda_simbolo": "US$",
    "moneda_decimales": "2",
    "moneda_porcentaje_variacion": "5",

  },
  {
    "moneda_clave": "EUR",
    "moneda_nombre": "Euro",
    "moneda_nombre_singular": "euro",
    "moneda_nombre_plural": "euros",
    "moneda_denominacion": "",
    "moneda_simbolo": "EUR",
    "moneda_decimales": "2",
    "moneda_porcentaje_variacion": "5",
  },
  {
    "moneda_clave": "ARS",
    "moneda_nombre": "Peso Argentino",
    "moneda_nombre_singular": "",
    "moneda_nombre_plural": "",
    "moneda_denominacion": "",
    "moneda_simbolo": "",
    "moneda_decimales": "2",
    "moneda_porcentaje_variacion": "5",
  },
  {
    "moneda_clave": "CLP",
    "moneda_nombre": "Peso chileno",
    "moneda_nombre_singular": "",
    "moneda_nombre_plural": "",
    "moneda_denominacion": "",
    "moneda_simbolo": "",
    "moneda_decimales": "2",
    "moneda_porcentaje_variacion": "5",
  },
  {
   
    "moneda_clave": "COP",
    "moneda_nombre": "Peso Colombiano",
    "moneda_nombre_singular": "",
    "moneda_nombre_plural": "",
    "moneda_denominacion": "",
    "moneda_simbolo": "",
    "moneda_decimales": "2",
    "moneda_porcentaje_variacion": "5",
  },
  {
    "moneda_clave": "CUP",
    "moneda_nombre": "Peso Cubano",
    "moneda_nombre_singular": "",
    "moneda_nombre_plural": "",
    "moneda_denominacion": "",
    "moneda_simbolo": "",
    "moneda_decimales": "2",
    "moneda_porcentaje_variacion": "5",
  },
  {
  
    "moneda_clave": "GTQ",
    "moneda_nombre": "Quetzal",
    "moneda_nombre_singular": "",
    "moneda_nombre_plural": "",
    "moneda_denominacion": "",
    "moneda_simbolo": "",
    "moneda_decimales": "2",
    "moneda_porcentaje_variacion": "5",
  },

  {
    "moneda_clave": "TTD",
    "moneda_nombre": "Dólar de Trinidad y Tobago",
    "moneda_nombre_singular": "",
    "moneda_nombre_plural": "",
    "moneda_denominacion": "",
    "moneda_simbolo": "",
    "moneda_decimales": "2",
    "moneda_porcentaje_variacion": "5",
  },

  {
    "moneda_clave": "UYU",
    "moneda_nombre": "Peso Uruguayo",
    "moneda_nombre_singular": "",
    "moneda_nombre_plural": "",
    "moneda_denominacion": "",
    "moneda_simbolo": "",
    "moneda_decimales": "2",
    "moneda_porcentaje_variacion": "5",
  },

  {
    "moneda_clave": "VEF",
    "moneda_nombre": "Bolívar",
    "moneda_nombre_singular": "",
    "moneda_nombre_plural": "",
    "moneda_denominacion": "",
    "moneda_simbolo": "",
    "moneda_decimales": "2",
    "moneda_porcentaje_variacion": "5",
  },
]